#!/bin/bash


#Step 1: remove compiled files: $ rm -r /scratch/aquaplanet/MoistModel/compilation_parallel
#Step 2: ensure namelist variables are correct for the run in particular phys.nml
#Step 3: to run the model simply put the following into the terminal ./runjob  or to runwith and keep terminal output use ./runjob 2>&1 | tee "terminal.log"


#load appropriate modules

dir_path=/scratch/sit204/FMS2013/GFDLmoistModel/src/extra
source $dir_path/loadmodule
#module purge
#module load intel/13.0.0
#module load hdf5/1.8.11  
#module load netcdf-4.3.0-openmpi-intel   
#module load openmpi-intel	
module list

# Set stack size to unlimited
ulimit -s unlimited


#if ( ! -d log_files ) then
	# mkdir log_files
#endif


#i=0 (from 0-11) for a spin up. Start at i=12 or greater for an experiment

for ((i=0; i < 13; i++))	
	
do
	./runscript $i 
	error_code=$?
	if [ $error_code != 0 ]; then
		echo 'error somewhere in runscript'
		echo $error_code
		exit
        fi
	#mv terminal.log log_files/terminal.log.run$i 
done

echo finished
echo Notes on this run as follows:



