name: isca_env
channels:
- conda-forge
dependencies:
- dask
- f90nml
- fortran-compiler
- ipykernel
- jinja2
- libgfortran
- netcdf-fortran
- numpy
- openmpi
- pandas
- python=3.7
- pip
- pytest
- sh
- tqdm
- xarray
