name: isca_env
channels:
- conda-forge
dependencies:
- dask=2024.1.0
- f90nml=1.4.4
- fortran-compiler=1.7.0
- ipykernel=6.29.0
- jinja2=3.1.3
- libgfortran=3.0.0
- netcdf-fortran=4.6.1 
- numpy=1.26.3
- openmpi=4.1.6
- pandas=2.2.0
- python=3.12.1
- pip=23.3.2
- pytest=7.4.4 
- sh=2.0.6
- tqdm=4.66.1
- xarray=2024.1.1
